### ISSUE TITLE
Sass loaders?

### ISSUE THREAD

**Issue by liquidvisual** [BryanSchuetz/vue-jekyll#5]
Hello! How can I put ```<style lang="scss" scoped>``` in my .vue files?

**Comment by BryanSchuetz** [comment]
Not 100% sure what you're asking. If you want to scope styles to a component, you do it as you indicated above—using the `scoped` attribute in the style block. If you want to use a preprocessor, you need to add the `lang` attribute as you did above _and also_ add the corresponding loader in your web pack config. [SEE DOCUMENTATION HERE](https://vue-loader.vuejs.org/guide/pre-processors.html#sass) for more details.
