### ISSUE TITLE
Data folder not rebuilding when update

### ISSUE THREAD

**Issue by keepexploring** [BryanSchuetz/vue-jekyll#6]
I downloaded you app and can run locally on my computer. However, I notice that if I make changes to the data in app.yml file, it does not get automatically rebuild and in the build folder (the data in the build folder is not modified) - I have to delete the build folder and rebuild to get it to work. Would you be able to check if you are having the same issue? I expect there is an easy fix - is the issue in the webpack config?

Thanks!

**Comment by BryanSchuetz** [comment]
Assuming you're using the included scripts to manage the build process—Jekyll is being built with the `--incremental` flag turned on. The only dependencies tracked for incremental builds are `layouts` and `{% include %}` tags. So a page that iterates over `site.data.app`, which is what `data\data.json` does, wouldn't be updated when `_data/app.yml` is modified. Hope that makes some kind of sense.

You can remove the `--incremental` flag in the `buildit` script in `package.json` and see if that solves your issue.
